[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello = "E4tQxsb5k44fgSBHRTQqGEuPene2Ez6Z8JiGjd8NHSvj"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
